In [6]:
import pandas as pd
import numpy as np

In [7]:
pd.__version__

'2.2.3'

#### Datatype of Pandas

1.DataFrame : 2D Table with rows and columns

2.Series : 1D array-like , can hold any data type such as integers, strings, floating-point numbers, and Python objects

##### Creating DataFrame

In [8]:
data={
    "name":['Sunil','Anshu','Madhu'],
    "Age":[22,7,28]
}
df=pd.DataFrame(data)

In [25]:
df

    name  Age gender
0  Sunil   22   male
1  Anshu    7   male
2  Madhu   28   male

In [28]:
df['gender']=['male','Female','male']

In [30]:
df

    name  Age  gender
0  Sunil   22    male
1  Anshu    7  Female
2  Madhu   28    male

In [31]:
df.shape

(3, 3)

In [32]:
df.size

9

In [33]:
df.dtypes

name      object
Age        int64
gender    object
dtype: object

#### Reading Data from Files

 pd.read_csv(file_path, delimiter=','): Reads CSV (Comma Separated Value) file and returns a Pandas DataFrame

file_path: Path to csv file


delimiter: Symbol separating different columns (default=',')

In [36]:
titanic=pd.read_csv('Titanic_data.csv',nrows=20)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
name=titanic['Name']

In [39]:
type(name)

pandas.core.series.Series

In [41]:
name_age=titanic[['Name','Age']]
name_age.head(

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
12                     Saundercock, Mr. William Henry  20.0
13                        Andersson, Mr. Anders Johan  39.0
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
16                               Rice, Master. Eugene   2.0
17                       Williams, Mr. Charles Eugene   NaN
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
19                            Masselmani, Mrs. Fatima   NaN